/* Generated By:JJTree: Do not edit this line. .\PiParserTreeConstants.java */

package piviz.executionEngine;

public interface PiParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTAGENTDEFINITION = 2;
  public int JJTCOMPOSITION = 3;
  public int JJTSUMMATION = 4;
  public int JJTRESTRICTION = 5;
  public int JJTREPLICATION = 6;
  public int JJTDEFINEDAGENT = 7;
  public int JJTSEND = 8;
  public int JJTRECEIVE = 9;
  public int JJTTAU = 10;
  public int JJTMATCH = 11;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "AgentDefinition",
    "Composition",
    "Summation",
    "Restriction",
    "Replication",
    "DefinedAgent",
    "Send",
    "Receive",
    "Tau",
    "Match",
  };
}
