/* Generated By:JJTree&JavaCC: Do not edit this line. PiParserConstants.java */
package piviz.executionEngine;

public interface PiParserConstants {

  int EOF = 0;
  int INACTION = 7;
  int AGENT_ID = 8;
  int AGENT_TOK = 9;
  int TAU = 10;
  int EXEC = 11;
  int POOL_TOK = 12;
  int CHAN_ID = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"0\"",
    "<AGENT_ID>",
    "\"agent\"",
    "\"t\"",
    "\"exec\"",
    "\"pool\"",
    "<CHAN_ID>",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"()\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"|\"",
    "\"+\"",
    "\"^\"",
    "\"!\"",
    "\"\\\'\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"!=\"",
    "\"]\"",
    "\".\"",
  };

}
